package entities.pricingStrategy.hourlyCarPricingStrategy.strategies;

import entities.pricingStrategy.hourlyCarPricingStrategy.AbstractHourlyCarPricingStrategy;

public class EconomyHourlyCarPricingStrategy extends AbstractHourlyCarPricingStrategy {

}
